global:     
    scrape_interval: "5s" #Scrape metric from targets every 5 seconds

scrape_configs:
  - job_name: "prometheus"  # Scrape Prometheus on http://localhost:9090/metrics
    static_configs:
      - targets:
          - localhost:9090
  - job_name: "demo"        # Scrape three public demo service targets
    static_configs:
      - targets:
          - demo.promlabs.com:10000
          - demo.promlabs.com:10001
          - demo.promlabs.com:10002
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    scheme: http
    follow_redirects: true
    body_size_limit: 0
    sample_limit: 0
    label_limit: 0
    label_name_length_limit: 0
    label_value_length_limit: 0
    target_limit: 0